replicaCount: 1

image:
  repository: sondresjo/pyttogpanne-app
  pullPolicy: IfNotPresent
  tag: "v1.0.2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount: {}

automountServiceAccountToken: false

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

startupProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 5
  failureThreshold: 12

readinessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 20
  timeoutSeconds: 3
  failureThreshold: 3

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: pyttogpanne.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env: []
