replicaCount: 1

image:
  repository: sondresjo/nstuning-api
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: nstuning-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  enabled: true
  storageClass: "nfs"
  accessMode: ReadWriteMany
  size: 20Gi
  mountPath: /data/reports

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env: []
