replicaCount: 1

image:
  repository: sondresjo/nstuning-app
  pullPolicy: IfNotPresent
  tag: "v1.6.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: nstuning.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env: []
